export const IMAGES = {
  logo: require('@/assets/images/logo.png'),
  list: require('@/assets/images/List.png'),
  grid: require('@/assets/images/grid.png'),
  leftArrow: require('@/assets/images/left-arrow.png'),
  search: require('@/assets/images/Search.png'),
  weather: require('@/assets/images/weather.jpg'),
  leftArrowW: require('@/assets/images/w-Left-Arrow.png'),
  searchW: require('@/assets/images/w-Search.png'),
  dogs: require('@/assets/images/dogs.jpg'),
  babyNames: require('@/assets/images/baby-names.jpg'),
  refreshB: require('@/assets/images/BReplay.png'),
  refresh: require('@/assets/images/refresh.png'),
  plants: require('@/assets/images/plants.jpg'),
  recipes: require('@/assets/images/recipes.jpg'),
  quotes: require('@/assets/images/quotes.jpg'),
};
